services:
  db:
    image: postgres:15
    container_name: portfolio-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres`
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: portfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
